---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-parser-service
  labels:
    app: fdk-parser-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-parser-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-parser-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
    spec:
      containers:
        - name: fdk-parser-service
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: KAFKA_SCHEMA_REGISTRY
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: SCHEMA_REGISTRY
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: BROKERS
          image: fdk-parser-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 10Gi
