---
apiVersion: v1
kind: Service
metadata:
  name: fdk-parser-service
spec:
  selector:
    app: fdk-parser-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
