/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Information about the catalog a resource is a member of */
@org.apache.avro.specific.AvroGenerated
public class Catalog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6694721262369505562L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Catalog\",\"namespace\":\"no.digdir.fdk.model\",\"doc\":\"Information about the catalog a resource is a member of\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"doc\":\"Unique FDK identifier for the catalog\"},{\"name\":\"uri\",\"type\":[\"null\",\"string\"],\"doc\":\"URI for the catalog\"},{\"name\":\"publisher\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Publisher\",\"doc\":\"Publisher information\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"doc\":\"Unique identifier for the publisher\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LocalizedStrings\",\"doc\":\"Multilingual texts\",\"fields\":[{\"name\":\"no\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian'\"},{\"name\":\"nb\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian bokmål'\"},{\"name\":\"nn\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian nynorsk'\"},{\"name\":\"en\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in english'\"}]}],\"doc\":\"Multilingual name of the publisher\"},{\"name\":\"uri\",\"type\":[\"null\",\"string\"],\"doc\":\"URI of the publisher\"}]}],\"doc\":\"Publisher of the catalog\"},{\"name\":\"title\",\"type\":[\"null\",\"LocalizedStrings\"],\"doc\":\"Multilingual title of the catalog\"},{\"name\":\"description\",\"type\":[\"null\",\"LocalizedStrings\"],\"doc\":\"Multilingual description of the catalog\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Catalog> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Catalog> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Catalog> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Catalog> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Catalog> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Catalog to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Catalog from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Catalog instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Catalog fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique FDK identifier for the catalog */
  private java.lang.CharSequence id;
  /** URI for the catalog */
  private java.lang.CharSequence uri;
  /** Publisher of the catalog */
  private no.digdir.fdk.model.Publisher publisher;
  /** Multilingual title of the catalog */
  private no.digdir.fdk.model.LocalizedStrings title;
  /** Multilingual description of the catalog */
  private no.digdir.fdk.model.LocalizedStrings description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Catalog() {}

  /**
   * All-args constructor.
   * @param id Unique FDK identifier for the catalog
   * @param uri URI for the catalog
   * @param publisher Publisher of the catalog
   * @param title Multilingual title of the catalog
   * @param description Multilingual description of the catalog
   */
  public Catalog(java.lang.CharSequence id, java.lang.CharSequence uri, no.digdir.fdk.model.Publisher publisher, no.digdir.fdk.model.LocalizedStrings title, no.digdir.fdk.model.LocalizedStrings description) {
    this.id = id;
    this.uri = uri;
    this.publisher = publisher;
    this.title = title;
    this.description = description;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return uri;
    case 2: return publisher;
    case 3: return title;
    case 4: return description;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: uri = (java.lang.CharSequence)value$; break;
    case 2: publisher = (no.digdir.fdk.model.Publisher)value$; break;
    case 3: title = (no.digdir.fdk.model.LocalizedStrings)value$; break;
    case 4: description = (no.digdir.fdk.model.LocalizedStrings)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique FDK identifier for the catalog
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique FDK identifier for the catalog
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return URI for the catalog
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }


  /**
   * Sets the value of the 'uri' field.
   * URI for the catalog
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'publisher' field.
   * @return Publisher of the catalog
   */
  public no.digdir.fdk.model.Publisher getPublisher() {
    return publisher;
  }


  /**
   * Sets the value of the 'publisher' field.
   * Publisher of the catalog
   * @param value the value to set.
   */
  public void setPublisher(no.digdir.fdk.model.Publisher value) {
    this.publisher = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return Multilingual title of the catalog
   */
  public no.digdir.fdk.model.LocalizedStrings getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * Multilingual title of the catalog
   * @param value the value to set.
   */
  public void setTitle(no.digdir.fdk.model.LocalizedStrings value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return Multilingual description of the catalog
   */
  public no.digdir.fdk.model.LocalizedStrings getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * Multilingual description of the catalog
   * @param value the value to set.
   */
  public void setDescription(no.digdir.fdk.model.LocalizedStrings value) {
    this.description = value;
  }

  /**
   * Creates a new Catalog RecordBuilder.
   * @return A new Catalog RecordBuilder
   */
  public static no.digdir.fdk.model.Catalog.Builder newBuilder() {
    return new no.digdir.fdk.model.Catalog.Builder();
  }

  /**
   * Creates a new Catalog RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Catalog RecordBuilder
   */
  public static no.digdir.fdk.model.Catalog.Builder newBuilder(no.digdir.fdk.model.Catalog.Builder other) {
    if (other == null) {
      return new no.digdir.fdk.model.Catalog.Builder();
    } else {
      return new no.digdir.fdk.model.Catalog.Builder(other);
    }
  }

  /**
   * Creates a new Catalog RecordBuilder by copying an existing Catalog instance.
   * @param other The existing instance to copy.
   * @return A new Catalog RecordBuilder
   */
  public static no.digdir.fdk.model.Catalog.Builder newBuilder(no.digdir.fdk.model.Catalog other) {
    if (other == null) {
      return new no.digdir.fdk.model.Catalog.Builder();
    } else {
      return new no.digdir.fdk.model.Catalog.Builder(other);
    }
  }

  /**
   * RecordBuilder for Catalog instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Catalog>
    implements org.apache.avro.data.RecordBuilder<Catalog> {

    /** Unique FDK identifier for the catalog */
    private java.lang.CharSequence id;
    /** URI for the catalog */
    private java.lang.CharSequence uri;
    /** Publisher of the catalog */
    private no.digdir.fdk.model.Publisher publisher;
    private no.digdir.fdk.model.Publisher.Builder publisherBuilder;
    /** Multilingual title of the catalog */
    private no.digdir.fdk.model.LocalizedStrings title;
    private no.digdir.fdk.model.LocalizedStrings.Builder titleBuilder;
    /** Multilingual description of the catalog */
    private no.digdir.fdk.model.LocalizedStrings description;
    private no.digdir.fdk.model.LocalizedStrings.Builder descriptionBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.digdir.fdk.model.Catalog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.uri)) {
        this.uri = data().deepCopy(fields()[1].schema(), other.uri);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.publisher)) {
        this.publisher = data().deepCopy(fields()[2].schema(), other.publisher);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasPublisherBuilder()) {
        this.publisherBuilder = no.digdir.fdk.model.Publisher.newBuilder(other.getPublisherBuilder());
      }
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasTitleBuilder()) {
        this.titleBuilder = no.digdir.fdk.model.LocalizedStrings.newBuilder(other.getTitleBuilder());
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasDescriptionBuilder()) {
        this.descriptionBuilder = no.digdir.fdk.model.LocalizedStrings.newBuilder(other.getDescriptionBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Catalog instance
     * @param other The existing instance to copy.
     */
    private Builder(no.digdir.fdk.model.Catalog other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uri)) {
        this.uri = data().deepCopy(fields()[1].schema(), other.uri);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publisher)) {
        this.publisher = data().deepCopy(fields()[2].schema(), other.publisher);
        fieldSetFlags()[2] = true;
      }
      this.publisherBuilder = null;
      if (isValidValue(fields()[3], other.title)) {
        this.title = data().deepCopy(fields()[3].schema(), other.title);
        fieldSetFlags()[3] = true;
      }
      this.titleBuilder = null;
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
      this.descriptionBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * Unique FDK identifier for the catalog
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique FDK identifier for the catalog
      * @param value The value of 'id'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique FDK identifier for the catalog
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique FDK identifier for the catalog
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * URI for the catalog
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }


    /**
      * Sets the value of the 'uri' field.
      * URI for the catalog
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.uri = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * URI for the catalog
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'uri' field.
      * URI for the catalog
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder clearUri() {
      uri = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisher' field.
      * Publisher of the catalog
      * @return The value.
      */
    public no.digdir.fdk.model.Publisher getPublisher() {
      return publisher;
    }


    /**
      * Sets the value of the 'publisher' field.
      * Publisher of the catalog
      * @param value The value of 'publisher'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder setPublisher(no.digdir.fdk.model.Publisher value) {
      validate(fields()[2], value);
      this.publisherBuilder = null;
      this.publisher = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publisher' field has been set.
      * Publisher of the catalog
      * @return True if the 'publisher' field has been set, false otherwise.
      */
    public boolean hasPublisher() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'publisher' field and creates one if it doesn't exist yet.
     * Publisher of the catalog
     * @return This builder.
     */
    public no.digdir.fdk.model.Publisher.Builder getPublisherBuilder() {
      if (publisherBuilder == null) {
        if (hasPublisher()) {
          setPublisherBuilder(no.digdir.fdk.model.Publisher.newBuilder(publisher));
        } else {
          setPublisherBuilder(no.digdir.fdk.model.Publisher.newBuilder());
        }
      }
      return publisherBuilder;
    }

    /**
     * Sets the Builder instance for the 'publisher' field
     * Publisher of the catalog
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public no.digdir.fdk.model.Catalog.Builder setPublisherBuilder(no.digdir.fdk.model.Publisher.Builder value) {
      clearPublisher();
      publisherBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'publisher' field has an active Builder instance
     * Publisher of the catalog
     * @return True if the 'publisher' field has an active Builder instance
     */
    public boolean hasPublisherBuilder() {
      return publisherBuilder != null;
    }

    /**
      * Clears the value of the 'publisher' field.
      * Publisher of the catalog
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder clearPublisher() {
      publisher = null;
      publisherBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * Multilingual title of the catalog
      * @return The value.
      */
    public no.digdir.fdk.model.LocalizedStrings getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * Multilingual title of the catalog
      * @param value The value of 'title'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder setTitle(no.digdir.fdk.model.LocalizedStrings value) {
      validate(fields()[3], value);
      this.titleBuilder = null;
      this.title = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * Multilingual title of the catalog
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'title' field and creates one if it doesn't exist yet.
     * Multilingual title of the catalog
     * @return This builder.
     */
    public no.digdir.fdk.model.LocalizedStrings.Builder getTitleBuilder() {
      if (titleBuilder == null) {
        if (hasTitle()) {
          setTitleBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder(title));
        } else {
          setTitleBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder());
        }
      }
      return titleBuilder;
    }

    /**
     * Sets the Builder instance for the 'title' field
     * Multilingual title of the catalog
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public no.digdir.fdk.model.Catalog.Builder setTitleBuilder(no.digdir.fdk.model.LocalizedStrings.Builder value) {
      clearTitle();
      titleBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'title' field has an active Builder instance
     * Multilingual title of the catalog
     * @return True if the 'title' field has an active Builder instance
     */
    public boolean hasTitleBuilder() {
      return titleBuilder != null;
    }

    /**
      * Clears the value of the 'title' field.
      * Multilingual title of the catalog
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder clearTitle() {
      title = null;
      titleBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * Multilingual description of the catalog
      * @return The value.
      */
    public no.digdir.fdk.model.LocalizedStrings getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * Multilingual description of the catalog
      * @param value The value of 'description'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder setDescription(no.digdir.fdk.model.LocalizedStrings value) {
      validate(fields()[4], value);
      this.descriptionBuilder = null;
      this.description = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * Multilingual description of the catalog
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'description' field and creates one if it doesn't exist yet.
     * Multilingual description of the catalog
     * @return This builder.
     */
    public no.digdir.fdk.model.LocalizedStrings.Builder getDescriptionBuilder() {
      if (descriptionBuilder == null) {
        if (hasDescription()) {
          setDescriptionBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder(description));
        } else {
          setDescriptionBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder());
        }
      }
      return descriptionBuilder;
    }

    /**
     * Sets the Builder instance for the 'description' field
     * Multilingual description of the catalog
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public no.digdir.fdk.model.Catalog.Builder setDescriptionBuilder(no.digdir.fdk.model.LocalizedStrings.Builder value) {
      clearDescription();
      descriptionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'description' field has an active Builder instance
     * Multilingual description of the catalog
     * @return True if the 'description' field has an active Builder instance
     */
    public boolean hasDescriptionBuilder() {
      return descriptionBuilder != null;
    }

    /**
      * Clears the value of the 'description' field.
      * Multilingual description of the catalog
      * @return This builder.
      */
    public no.digdir.fdk.model.Catalog.Builder clearDescription() {
      description = null;
      descriptionBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Catalog build() {
      try {
        Catalog record = new Catalog();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.uri = fieldSetFlags()[1] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (publisherBuilder != null) {
          try {
            record.publisher = this.publisherBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("publisher"));
            throw e;
          }
        } else {
          record.publisher = fieldSetFlags()[2] ? this.publisher : (no.digdir.fdk.model.Publisher) defaultValue(fields()[2]);
        }
        if (titleBuilder != null) {
          try {
            record.title = this.titleBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("title"));
            throw e;
          }
        } else {
          record.title = fieldSetFlags()[3] ? this.title : (no.digdir.fdk.model.LocalizedStrings) defaultValue(fields()[3]);
        }
        if (descriptionBuilder != null) {
          try {
            record.description = this.descriptionBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("description"));
            throw e;
          }
        } else {
          record.description = fieldSetFlags()[4] ? this.description : (no.digdir.fdk.model.LocalizedStrings) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Catalog>
    WRITER$ = (org.apache.avro.io.DatumWriter<Catalog>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Catalog>
    READER$ = (org.apache.avro.io.DatumReader<Catalog>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.uri == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.uri);
    }

    if (this.publisher == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.publisher.customEncode(out);
    }

    if (this.title == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.title.customEncode(out);
    }

    if (this.description == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.description.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.uri = null;
      } else {
        this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.publisher = null;
      } else {
        if (this.publisher == null) {
          this.publisher = new no.digdir.fdk.model.Publisher();
        }
        this.publisher.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.title = null;
      } else {
        if (this.title == null) {
          this.title = new no.digdir.fdk.model.LocalizedStrings();
        }
        this.title.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.description = null;
      } else {
        if (this.description == null) {
          this.description = new no.digdir.fdk.model.LocalizedStrings();
        }
        this.description.customDecode(in);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.uri = null;
          } else {
            this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.publisher = null;
          } else {
            if (this.publisher == null) {
              this.publisher = new no.digdir.fdk.model.Publisher();
            }
            this.publisher.customDecode(in);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.title = null;
          } else {
            if (this.title == null) {
              this.title = new no.digdir.fdk.model.LocalizedStrings();
            }
            this.title.customDecode(in);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.description = null;
          } else {
            if (this.description == null) {
              this.description = new no.digdir.fdk.model.LocalizedStrings();
            }
            this.description.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










