/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;
@org.apache.avro.specific.AvroGenerated
public enum FormatType implements org.apache.avro.generic.GenericEnumSymbol<FormatType> {
  UNKNOWN, MEDIA_TYPE, FILE_TYPE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FormatType\",\"namespace\":\"no.digdir.fdk.model\",\"symbols\":[\"UNKNOWN\",\"MEDIA_TYPE\",\"FILE_TYPE\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
