/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Meta data from the harvest of the resource to FDK */
@org.apache.avro.specific.AvroGenerated
public class HarvestMetaData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3551515461668042045L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HarvestMetaData\",\"namespace\":\"no.digdir.fdk.model\",\"doc\":\"Meta data from the harvest of the resource to FDK\",\"fields\":[{\"name\":\"firstHarvested\",\"type\":[\"null\",\"string\"],\"doc\":\"Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'\"},{\"name\":\"modified\",\"type\":[\"null\",\"string\"],\"doc\":\"Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HarvestMetaData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HarvestMetaData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HarvestMetaData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HarvestMetaData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HarvestMetaData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HarvestMetaData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HarvestMetaData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HarvestMetaData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HarvestMetaData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ' */
  private java.lang.CharSequence firstHarvested;
  /** Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ' */
  private java.lang.CharSequence modified;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HarvestMetaData() {}

  /**
   * All-args constructor.
   * @param firstHarvested Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
   * @param modified Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
   */
  public HarvestMetaData(java.lang.CharSequence firstHarvested, java.lang.CharSequence modified) {
    this.firstHarvested = firstHarvested;
    this.modified = modified;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstHarvested;
    case 1: return modified;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstHarvested = (java.lang.CharSequence)value$; break;
    case 1: modified = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'firstHarvested' field.
   * @return Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
   */
  public java.lang.CharSequence getFirstHarvested() {
    return firstHarvested;
  }


  /**
   * Sets the value of the 'firstHarvested' field.
   * Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
   * @param value the value to set.
   */
  public void setFirstHarvested(java.lang.CharSequence value) {
    this.firstHarvested = value;
  }

  /**
   * Gets the value of the 'modified' field.
   * @return Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
   */
  public java.lang.CharSequence getModified() {
    return modified;
  }


  /**
   * Sets the value of the 'modified' field.
   * Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
   * @param value the value to set.
   */
  public void setModified(java.lang.CharSequence value) {
    this.modified = value;
  }

  /**
   * Creates a new HarvestMetaData RecordBuilder.
   * @return A new HarvestMetaData RecordBuilder
   */
  public static no.digdir.fdk.model.HarvestMetaData.Builder newBuilder() {
    return new no.digdir.fdk.model.HarvestMetaData.Builder();
  }

  /**
   * Creates a new HarvestMetaData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HarvestMetaData RecordBuilder
   */
  public static no.digdir.fdk.model.HarvestMetaData.Builder newBuilder(no.digdir.fdk.model.HarvestMetaData.Builder other) {
    if (other == null) {
      return new no.digdir.fdk.model.HarvestMetaData.Builder();
    } else {
      return new no.digdir.fdk.model.HarvestMetaData.Builder(other);
    }
  }

  /**
   * Creates a new HarvestMetaData RecordBuilder by copying an existing HarvestMetaData instance.
   * @param other The existing instance to copy.
   * @return A new HarvestMetaData RecordBuilder
   */
  public static no.digdir.fdk.model.HarvestMetaData.Builder newBuilder(no.digdir.fdk.model.HarvestMetaData other) {
    if (other == null) {
      return new no.digdir.fdk.model.HarvestMetaData.Builder();
    } else {
      return new no.digdir.fdk.model.HarvestMetaData.Builder(other);
    }
  }

  /**
   * RecordBuilder for HarvestMetaData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HarvestMetaData>
    implements org.apache.avro.data.RecordBuilder<HarvestMetaData> {

    /** Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ' */
    private java.lang.CharSequence firstHarvested;
    /** Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ' */
    private java.lang.CharSequence modified;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.digdir.fdk.model.HarvestMetaData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstHarvested)) {
        this.firstHarvested = data().deepCopy(fields()[0].schema(), other.firstHarvested);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.modified)) {
        this.modified = data().deepCopy(fields()[1].schema(), other.modified);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing HarvestMetaData instance
     * @param other The existing instance to copy.
     */
    private Builder(no.digdir.fdk.model.HarvestMetaData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.firstHarvested)) {
        this.firstHarvested = data().deepCopy(fields()[0].schema(), other.firstHarvested);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.modified)) {
        this.modified = data().deepCopy(fields()[1].schema(), other.modified);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'firstHarvested' field.
      * Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return The value.
      */
    public java.lang.CharSequence getFirstHarvested() {
      return firstHarvested;
    }


    /**
      * Sets the value of the 'firstHarvested' field.
      * Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @param value The value of 'firstHarvested'.
      * @return This builder.
      */
    public no.digdir.fdk.model.HarvestMetaData.Builder setFirstHarvested(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstHarvested = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstHarvested' field has been set.
      * Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return True if the 'firstHarvested' field has been set, false otherwise.
      */
    public boolean hasFirstHarvested() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstHarvested' field.
      * Date when the resource was first harvested to FDK, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return This builder.
      */
    public no.digdir.fdk.model.HarvestMetaData.Builder clearFirstHarvested() {
      firstHarvested = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'modified' field.
      * Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return The value.
      */
    public java.lang.CharSequence getModified() {
      return modified;
    }


    /**
      * Sets the value of the 'modified' field.
      * Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @param value The value of 'modified'.
      * @return This builder.
      */
    public no.digdir.fdk.model.HarvestMetaData.Builder setModified(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.modified = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'modified' field has been set.
      * Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return True if the 'modified' field has been set, false otherwise.
      */
    public boolean hasModified() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'modified' field.
      * Date when the harvest process last found changes to the resource, format: 'YYYY-MM-DDTHH:mm:ssZ'
      * @return This builder.
      */
    public no.digdir.fdk.model.HarvestMetaData.Builder clearModified() {
      modified = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HarvestMetaData build() {
      try {
        HarvestMetaData record = new HarvestMetaData();
        record.firstHarvested = fieldSetFlags()[0] ? this.firstHarvested : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.modified = fieldSetFlags()[1] ? this.modified : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HarvestMetaData>
    WRITER$ = (org.apache.avro.io.DatumWriter<HarvestMetaData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HarvestMetaData>
    READER$ = (org.apache.avro.io.DatumReader<HarvestMetaData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.firstHarvested == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.firstHarvested);
    }

    if (this.modified == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.modified);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.firstHarvested = null;
      } else {
        this.firstHarvested = in.readString(this.firstHarvested instanceof Utf8 ? (Utf8)this.firstHarvested : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.modified = null;
      } else {
        this.modified = in.readString(this.modified instanceof Utf8 ? (Utf8)this.modified : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.firstHarvested = null;
          } else {
            this.firstHarvested = in.readString(this.firstHarvested instanceof Utf8 ? (Utf8)this.firstHarvested : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.modified = null;
          } else {
            this.modified = in.readString(this.modified instanceof Utf8 ? (Utf8)this.modified : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










