/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** LOS theme information */
@org.apache.avro.specific.AvroGenerated
public class LosNode extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6951877013926297016L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LosNode\",\"namespace\":\"no.digdir.fdk.model\",\"doc\":\"LOS theme information\",\"fields\":[{\"name\":\"uri\",\"type\":[\"null\",\"string\"],\"doc\":\"URI of the theme\"},{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"doc\":\"Code value for the theme\"},{\"name\":\"isTema\",\"type\":[\"null\",\"boolean\"],\"doc\":\"Is LOS theme or LOS word\"},{\"name\":\"losPaths\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"doc\":\"LOS hierarchy paths for the theme\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LocalizedStrings\",\"doc\":\"Multilingual texts\",\"fields\":[{\"name\":\"no\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian'\"},{\"name\":\"nb\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian bokmål'\"},{\"name\":\"nn\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian nynorsk'\"},{\"name\":\"en\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in english'\"}]}],\"doc\":\"Multilingual name of the theme\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LosNode> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LosNode> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LosNode> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LosNode> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LosNode> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LosNode to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LosNode from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LosNode instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LosNode fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** URI of the theme */
  private java.lang.CharSequence uri;
  /** Code value for the theme */
  private java.lang.CharSequence code;
  /** Is LOS theme or LOS word */
  private java.lang.Boolean isTema;
  /** LOS hierarchy paths for the theme */
  private java.util.List<java.lang.CharSequence> losPaths;
  /** Multilingual name of the theme */
  private no.digdir.fdk.model.LocalizedStrings name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LosNode() {}

  /**
   * All-args constructor.
   * @param uri URI of the theme
   * @param code Code value for the theme
   * @param isTema Is LOS theme or LOS word
   * @param losPaths LOS hierarchy paths for the theme
   * @param name Multilingual name of the theme
   */
  public LosNode(java.lang.CharSequence uri, java.lang.CharSequence code, java.lang.Boolean isTema, java.util.List<java.lang.CharSequence> losPaths, no.digdir.fdk.model.LocalizedStrings name) {
    this.uri = uri;
    this.code = code;
    this.isTema = isTema;
    this.losPaths = losPaths;
    this.name = name;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return code;
    case 2: return isTema;
    case 3: return losPaths;
    case 4: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: code = (java.lang.CharSequence)value$; break;
    case 2: isTema = (java.lang.Boolean)value$; break;
    case 3: losPaths = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: name = (no.digdir.fdk.model.LocalizedStrings)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'uri' field.
   * @return URI of the theme
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }


  /**
   * Sets the value of the 'uri' field.
   * URI of the theme
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return Code value for the theme
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * Code value for the theme
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'isTema' field.
   * @return Is LOS theme or LOS word
   */
  public java.lang.Boolean getIsTema() {
    return isTema;
  }


  /**
   * Sets the value of the 'isTema' field.
   * Is LOS theme or LOS word
   * @param value the value to set.
   */
  public void setIsTema(java.lang.Boolean value) {
    this.isTema = value;
  }

  /**
   * Gets the value of the 'losPaths' field.
   * @return LOS hierarchy paths for the theme
   */
  public java.util.List<java.lang.CharSequence> getLosPaths() {
    return losPaths;
  }


  /**
   * Sets the value of the 'losPaths' field.
   * LOS hierarchy paths for the theme
   * @param value the value to set.
   */
  public void setLosPaths(java.util.List<java.lang.CharSequence> value) {
    this.losPaths = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Multilingual name of the theme
   */
  public no.digdir.fdk.model.LocalizedStrings getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Multilingual name of the theme
   * @param value the value to set.
   */
  public void setName(no.digdir.fdk.model.LocalizedStrings value) {
    this.name = value;
  }

  /**
   * Creates a new LosNode RecordBuilder.
   * @return A new LosNode RecordBuilder
   */
  public static no.digdir.fdk.model.LosNode.Builder newBuilder() {
    return new no.digdir.fdk.model.LosNode.Builder();
  }

  /**
   * Creates a new LosNode RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LosNode RecordBuilder
   */
  public static no.digdir.fdk.model.LosNode.Builder newBuilder(no.digdir.fdk.model.LosNode.Builder other) {
    if (other == null) {
      return new no.digdir.fdk.model.LosNode.Builder();
    } else {
      return new no.digdir.fdk.model.LosNode.Builder(other);
    }
  }

  /**
   * Creates a new LosNode RecordBuilder by copying an existing LosNode instance.
   * @param other The existing instance to copy.
   * @return A new LosNode RecordBuilder
   */
  public static no.digdir.fdk.model.LosNode.Builder newBuilder(no.digdir.fdk.model.LosNode other) {
    if (other == null) {
      return new no.digdir.fdk.model.LosNode.Builder();
    } else {
      return new no.digdir.fdk.model.LosNode.Builder(other);
    }
  }

  /**
   * RecordBuilder for LosNode instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LosNode>
    implements org.apache.avro.data.RecordBuilder<LosNode> {

    /** URI of the theme */
    private java.lang.CharSequence uri;
    /** Code value for the theme */
    private java.lang.CharSequence code;
    /** Is LOS theme or LOS word */
    private java.lang.Boolean isTema;
    /** LOS hierarchy paths for the theme */
    private java.util.List<java.lang.CharSequence> losPaths;
    /** Multilingual name of the theme */
    private no.digdir.fdk.model.LocalizedStrings name;
    private no.digdir.fdk.model.LocalizedStrings.Builder nameBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.digdir.fdk.model.LosNode.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.isTema)) {
        this.isTema = data().deepCopy(fields()[2].schema(), other.isTema);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.losPaths)) {
        this.losPaths = data().deepCopy(fields()[3].schema(), other.losPaths);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.name)) {
        this.name = data().deepCopy(fields()[4].schema(), other.name);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasNameBuilder()) {
        this.nameBuilder = no.digdir.fdk.model.LocalizedStrings.newBuilder(other.getNameBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing LosNode instance
     * @param other The existing instance to copy.
     */
    private Builder(no.digdir.fdk.model.LosNode other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isTema)) {
        this.isTema = data().deepCopy(fields()[2].schema(), other.isTema);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.losPaths)) {
        this.losPaths = data().deepCopy(fields()[3].schema(), other.losPaths);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.name)) {
        this.name = data().deepCopy(fields()[4].schema(), other.name);
        fieldSetFlags()[4] = true;
      }
      this.nameBuilder = null;
    }

    /**
      * Gets the value of the 'uri' field.
      * URI of the theme
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }


    /**
      * Sets the value of the 'uri' field.
      * URI of the theme
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * URI of the theme
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uri' field.
      * URI of the theme
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * Code value for the theme
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * Code value for the theme
      * @param value The value of 'code'.
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * Code value for the theme
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * Code value for the theme
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'isTema' field.
      * Is LOS theme or LOS word
      * @return The value.
      */
    public java.lang.Boolean getIsTema() {
      return isTema;
    }


    /**
      * Sets the value of the 'isTema' field.
      * Is LOS theme or LOS word
      * @param value The value of 'isTema'.
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder setIsTema(java.lang.Boolean value) {
      validate(fields()[2], value);
      this.isTema = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'isTema' field has been set.
      * Is LOS theme or LOS word
      * @return True if the 'isTema' field has been set, false otherwise.
      */
    public boolean hasIsTema() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'isTema' field.
      * Is LOS theme or LOS word
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder clearIsTema() {
      isTema = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'losPaths' field.
      * LOS hierarchy paths for the theme
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getLosPaths() {
      return losPaths;
    }


    /**
      * Sets the value of the 'losPaths' field.
      * LOS hierarchy paths for the theme
      * @param value The value of 'losPaths'.
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder setLosPaths(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.losPaths = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'losPaths' field has been set.
      * LOS hierarchy paths for the theme
      * @return True if the 'losPaths' field has been set, false otherwise.
      */
    public boolean hasLosPaths() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'losPaths' field.
      * LOS hierarchy paths for the theme
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder clearLosPaths() {
      losPaths = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Multilingual name of the theme
      * @return The value.
      */
    public no.digdir.fdk.model.LocalizedStrings getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Multilingual name of the theme
      * @param value The value of 'name'.
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder setName(no.digdir.fdk.model.LocalizedStrings value) {
      validate(fields()[4], value);
      this.nameBuilder = null;
      this.name = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Multilingual name of the theme
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'name' field and creates one if it doesn't exist yet.
     * Multilingual name of the theme
     * @return This builder.
     */
    public no.digdir.fdk.model.LocalizedStrings.Builder getNameBuilder() {
      if (nameBuilder == null) {
        if (hasName()) {
          setNameBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder(name));
        } else {
          setNameBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder());
        }
      }
      return nameBuilder;
    }

    /**
     * Sets the Builder instance for the 'name' field
     * Multilingual name of the theme
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public no.digdir.fdk.model.LosNode.Builder setNameBuilder(no.digdir.fdk.model.LocalizedStrings.Builder value) {
      clearName();
      nameBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'name' field has an active Builder instance
     * Multilingual name of the theme
     * @return True if the 'name' field has an active Builder instance
     */
    public boolean hasNameBuilder() {
      return nameBuilder != null;
    }

    /**
      * Clears the value of the 'name' field.
      * Multilingual name of the theme
      * @return This builder.
      */
    public no.digdir.fdk.model.LosNode.Builder clearName() {
      name = null;
      nameBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LosNode build() {
      try {
        LosNode record = new LosNode();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.isTema = fieldSetFlags()[2] ? this.isTema : (java.lang.Boolean) defaultValue(fields()[2]);
        record.losPaths = fieldSetFlags()[3] ? this.losPaths : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        if (nameBuilder != null) {
          try {
            record.name = this.nameBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("name"));
            throw e;
          }
        } else {
          record.name = fieldSetFlags()[4] ? this.name : (no.digdir.fdk.model.LocalizedStrings) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LosNode>
    WRITER$ = (org.apache.avro.io.DatumWriter<LosNode>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LosNode>
    READER$ = (org.apache.avro.io.DatumReader<LosNode>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.uri == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.uri);
    }

    if (this.code == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.code);
    }

    if (this.isTema == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.isTema);
    }

    if (this.losPaths == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.losPaths.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.CharSequence e0: this.losPaths) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.name.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.uri = null;
      } else {
        this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.code = null;
      } else {
        this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.isTema = null;
      } else {
        this.isTema = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.losPaths = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.CharSequence> a0 = this.losPaths;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("losPaths").schema().getTypes().get(1));
          this.losPaths = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
            a0.add(e0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        if (this.name == null) {
          this.name = new no.digdir.fdk.model.LocalizedStrings();
        }
        this.name.customDecode(in);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.uri = null;
          } else {
            this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.code = null;
          } else {
            this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.isTema = null;
          } else {
            this.isTema = in.readBoolean();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.losPaths = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.CharSequence> a0 = this.losPaths;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("losPaths").schema().getTypes().get(1));
              this.losPaths = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
                a0.add(e0);
              }
            }
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            if (this.name == null) {
              this.name = new no.digdir.fdk.model.LocalizedStrings();
            }
            this.name.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










