/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Publisher information */
@org.apache.avro.specific.AvroGenerated
public class Publisher extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 550157172023618849L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Publisher\",\"namespace\":\"no.digdir.fdk.model\",\"doc\":\"Publisher information\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"doc\":\"Unique identifier for the publisher\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LocalizedStrings\",\"doc\":\"Multilingual texts\",\"fields\":[{\"name\":\"no\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian'\"},{\"name\":\"nb\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian bokmål'\"},{\"name\":\"nn\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in norwegian nynorsk'\"},{\"name\":\"en\",\"type\":[\"null\",\"string\"],\"doc\":\"Text in english'\"}]}],\"doc\":\"Multilingual name of the publisher\"},{\"name\":\"uri\",\"type\":[\"null\",\"string\"],\"doc\":\"URI of the publisher\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Publisher> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Publisher> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Publisher> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Publisher> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Publisher> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Publisher to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Publisher from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Publisher instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Publisher fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the publisher */
  private java.lang.CharSequence id;
  /** Multilingual name of the publisher */
  private no.digdir.fdk.model.LocalizedStrings name;
  /** URI of the publisher */
  private java.lang.CharSequence uri;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Publisher() {}

  /**
   * All-args constructor.
   * @param id Unique identifier for the publisher
   * @param name Multilingual name of the publisher
   * @param uri URI of the publisher
   */
  public Publisher(java.lang.CharSequence id, no.digdir.fdk.model.LocalizedStrings name, java.lang.CharSequence uri) {
    this.id = id;
    this.name = name;
    this.uri = uri;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return uri;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (no.digdir.fdk.model.LocalizedStrings)value$; break;
    case 2: uri = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique identifier for the publisher
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique identifier for the publisher
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Multilingual name of the publisher
   */
  public no.digdir.fdk.model.LocalizedStrings getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Multilingual name of the publisher
   * @param value the value to set.
   */
  public void setName(no.digdir.fdk.model.LocalizedStrings value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return URI of the publisher
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }


  /**
   * Sets the value of the 'uri' field.
   * URI of the publisher
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Creates a new Publisher RecordBuilder.
   * @return A new Publisher RecordBuilder
   */
  public static no.digdir.fdk.model.Publisher.Builder newBuilder() {
    return new no.digdir.fdk.model.Publisher.Builder();
  }

  /**
   * Creates a new Publisher RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Publisher RecordBuilder
   */
  public static no.digdir.fdk.model.Publisher.Builder newBuilder(no.digdir.fdk.model.Publisher.Builder other) {
    if (other == null) {
      return new no.digdir.fdk.model.Publisher.Builder();
    } else {
      return new no.digdir.fdk.model.Publisher.Builder(other);
    }
  }

  /**
   * Creates a new Publisher RecordBuilder by copying an existing Publisher instance.
   * @param other The existing instance to copy.
   * @return A new Publisher RecordBuilder
   */
  public static no.digdir.fdk.model.Publisher.Builder newBuilder(no.digdir.fdk.model.Publisher other) {
    if (other == null) {
      return new no.digdir.fdk.model.Publisher.Builder();
    } else {
      return new no.digdir.fdk.model.Publisher.Builder(other);
    }
  }

  /**
   * RecordBuilder for Publisher instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Publisher>
    implements org.apache.avro.data.RecordBuilder<Publisher> {

    /** Unique identifier for the publisher */
    private java.lang.CharSequence id;
    /** Multilingual name of the publisher */
    private no.digdir.fdk.model.LocalizedStrings name;
    private no.digdir.fdk.model.LocalizedStrings.Builder nameBuilder;
    /** URI of the publisher */
    private java.lang.CharSequence uri;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.digdir.fdk.model.Publisher.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasNameBuilder()) {
        this.nameBuilder = no.digdir.fdk.model.LocalizedStrings.newBuilder(other.getNameBuilder());
      }
      if (isValidValue(fields()[2], other.uri)) {
        this.uri = data().deepCopy(fields()[2].schema(), other.uri);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Publisher instance
     * @param other The existing instance to copy.
     */
    private Builder(no.digdir.fdk.model.Publisher other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      this.nameBuilder = null;
      if (isValidValue(fields()[2], other.uri)) {
        this.uri = data().deepCopy(fields()[2].schema(), other.uri);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Unique identifier for the publisher
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique identifier for the publisher
      * @param value The value of 'id'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique identifier for the publisher
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique identifier for the publisher
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Multilingual name of the publisher
      * @return The value.
      */
    public no.digdir.fdk.model.LocalizedStrings getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Multilingual name of the publisher
      * @param value The value of 'name'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder setName(no.digdir.fdk.model.LocalizedStrings value) {
      validate(fields()[1], value);
      this.nameBuilder = null;
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Multilingual name of the publisher
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'name' field and creates one if it doesn't exist yet.
     * Multilingual name of the publisher
     * @return This builder.
     */
    public no.digdir.fdk.model.LocalizedStrings.Builder getNameBuilder() {
      if (nameBuilder == null) {
        if (hasName()) {
          setNameBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder(name));
        } else {
          setNameBuilder(no.digdir.fdk.model.LocalizedStrings.newBuilder());
        }
      }
      return nameBuilder;
    }

    /**
     * Sets the Builder instance for the 'name' field
     * Multilingual name of the publisher
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public no.digdir.fdk.model.Publisher.Builder setNameBuilder(no.digdir.fdk.model.LocalizedStrings.Builder value) {
      clearName();
      nameBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'name' field has an active Builder instance
     * Multilingual name of the publisher
     * @return True if the 'name' field has an active Builder instance
     */
    public boolean hasNameBuilder() {
      return nameBuilder != null;
    }

    /**
      * Clears the value of the 'name' field.
      * Multilingual name of the publisher
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder clearName() {
      name = null;
      nameBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * URI of the publisher
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }


    /**
      * Sets the value of the 'uri' field.
      * URI of the publisher
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.uri = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * URI of the publisher
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'uri' field.
      * URI of the publisher
      * @return This builder.
      */
    public no.digdir.fdk.model.Publisher.Builder clearUri() {
      uri = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Publisher build() {
      try {
        Publisher record = new Publisher();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (nameBuilder != null) {
          try {
            record.name = this.nameBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("name"));
            throw e;
          }
        } else {
          record.name = fieldSetFlags()[1] ? this.name : (no.digdir.fdk.model.LocalizedStrings) defaultValue(fields()[1]);
        }
        record.uri = fieldSetFlags()[2] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Publisher>
    WRITER$ = (org.apache.avro.io.DatumWriter<Publisher>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Publisher>
    READER$ = (org.apache.avro.io.DatumReader<Publisher>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.name.customEncode(out);
    }

    if (this.uri == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.uri);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        if (this.name == null) {
          this.name = new no.digdir.fdk.model.LocalizedStrings();
        }
        this.name.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.uri = null;
      } else {
        this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            if (this.name == null) {
              this.name = new no.digdir.fdk.model.LocalizedStrings();
            }
            this.name.customDecode(in);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.uri = null;
          } else {
            this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










