/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.digdir.fdk.model;
/** Types for resources in FDK */
@org.apache.avro.specific.AvroGenerated
public enum ResourceType implements org.apache.avro.generic.GenericEnumSymbol<ResourceType> {
  datasets  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ResourceType\",\"namespace\":\"no.digdir.fdk.model\",\"doc\":\"Types for resources in FDK\",\"symbols\":[\"datasets\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
